### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by twada** [twada/expect-js-to-assert#1]
#### matchers

- [x] `.ok()`
- [x] `.be(value)` (alias `.equal`)
- [x] `.eql(value)`
- [ ] `.a(type)` (alias `.an`)
- [x] `.match(regexp)`
- [x] `.contain(needle)`
- [x] `.length(size)`
- [ ] `.empty()`
- [ ] `.property(name, [value])`
- [ ] `.key(name)`
- [ ] `.keys(...name)`
- [x] `.throw([Function|RegExp])` (alias `.throwException`, `.throwError`) -> #2
- [x] `.within(start, finish)`
- [x] `.above(value)` (alias `.greaterThan`)
- [x] `.below(value)` (alias `.lessThan`)
- [ ] `.fail([reason])`

#### chains

- [x] `.not`
- [ ] `.withArgs(...args)`

**Comment by popomore** [comment]
throw https://github.com/twada/expect-js-to-assert/pull/2

**Comment by SAGV** [comment]
Ooohhhh, man! You've just saved me weeks of work!
